
POST http://localhost:3000/ginesys/item-master
Content-Type: application/json

{
    "username":"Rafique1",
    "password":"Rafique123"
}

###

POST http://localhost:3000/ginesys/inventory
Content-Type: application/json

{
    "username":"Rafique2",
    "password":"Rafique123"
}

###

POST http://localhost:3000/ginesys/online-invoice
Content-Type: application/json

{
    "username":"Rafique3",
    "password":"Rafique123"
}

###

POST http://localhost:3000/ginesys/pos-bill
Content-Type: application/json

{
    "username":"Rafique4",
    "password":"Rafique123"
}